export type Format = "ODI" | "T20" | "Test"
export type Role = "Batsman" | "Bowler" | "All-rounder" | "Wicket-keeper"
export type PlayerGroup = "Group A" | "Group B" | "Group C"

export interface PlayerStats {
  runs: number
  average: number
  strikeRate: number
  wickets: number
  economy: number
  catches: number
}

export interface Player {
  id: string
  name: string
  role: Role
  number: number
  country: string
  group: PlayerGroup
  stats: {
    ODI: PlayerStats
    T20: PlayerStats
    Test: PlayerStats
  }
  strengths: string[]
  weaknesses: string[]
  form: "Excellent" | "Good" | "Average" | "Poor"
  recentForm: number[]
  formatAvailability: {
    ODI: boolean
    T20: boolean
    Test: boolean
  }
}

export interface OppositionPlayer {
  name: string
  role: Role
  strengths: string[]
  weaknesses: string[]
  recentForm: number[]
}

export const indiaSquad: Player[] = [
  // GROUP A - SENIOR/EXPERIENCED PLAYERS
  {
    id: "virat",
    name: "Virat Kohli",
    role: "Batsman",
    number: 18,
    country: "India",
    group: "Group A",
    stats: {
      ODI: { runs: 13200, average: 59.2, strikeRate: 93.8, wickets: 0, economy: 0, catches: 48 },
      T20: { runs: 3850, average: 52.8, strikeRate: 137.2, wickets: 0, economy: 0, catches: 28 },
      Test: { runs: 8600, average: 54.5, strikeRate: 55.1, wickets: 0, economy: 0, catches: 36 },
    },
    strengths: ["Consistency", "Aggressive batting", "Pressure situations", "Leadership"],
    weaknesses: ["Short balls", "Yorkers", "Left-arm pace"],
    form: "Excellent",
    recentForm: [98, 85, 92, 78, 95],
    formatAvailability: { ODI: true, T20: false, Test: false },
  },
  {
    id: "rohit",
    name: "Rohit Sharma",
    role: "Batsman",
    number: 45,
    country: "India",
    group: "Group A",
    stats: {
      ODI: { runs: 10500, average: 50.2, strikeRate: 91.5, wickets: 0, economy: 0, catches: 35 },
      T20: { runs: 3800, average: 51.4, strikeRate: 140.5, wickets: 0, economy: 0, catches: 25 },
      Test: { runs: 7100, average: 47.3, strikeRate: 58.5, wickets: 0, economy: 0, catches: 32 },
    },
    strengths: ["Opening play", "Square drives", "Consistency", "Match awareness"],
    weaknesses: ["Yorkers", "Line and length", "Bounce"],
    form: "Good",
    recentForm: [82, 91, 75, 88, 72],
    formatAvailability: { ODI: true, T20: false, Test: false },
  },
  {
    id: "jasprit",
    name: "Jasprit Bumrah",
    role: "Bowler",
    number: 93,
    country: "India",
    group: "Group A",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 125, economy: 4.4, catches: 6 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 102, economy: 6.1, catches: 4 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 95, economy: 2.7, catches: 3 },
    },
    strengths: ["Yorkers", "Death bowling", "Accuracy", "Test bowling", "Pace"],
    weaknesses: ["Injury history", "Early overs", "Conventional pace"],
    form: "Excellent",
    recentForm: [92, 88, 95, 85, 90],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "mohammed-shami",
    name: "Mohammed Shami",
    role: "Bowler",
    number: 99,
    country: "India",
    group: "Group A",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 120, economy: 5.0, catches: 9 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 85, economy: 7.4, catches: 5 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 105, economy: 3.1, catches: 4 },
    },
    strengths: ["Swing bowling", "Pace", "Test expertise", "New ball bowling"],
    weaknesses: ["Death overs", "Injury prone", "Consistency"],
    form: "Good",
    recentForm: [85, 79, 88, 76, 82],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "r-ashwin",
    name: "R. Ashwin",
    role: "Bowler",
    number: 26,
    country: "India",
    group: "Group A",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 110, economy: 5.4, catches: 6 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 52, economy: 8.1, catches: 2 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 537, economy: 2.9, catches: 178 },
    },
    strengths: ["Off-spin", "Test expertise", "Experience", "Variations"],
    weaknesses: ["T20 form", "Pace bowling", "Bounce"],
    form: "Good",
    recentForm: [72, 75, 78, 70, 74],
    formatAvailability: { ODI: true, T20: false, Test: true },
  },

  // GROUP B - CORE PLAYERS
  {
    id: "shubman",
    name: "Shubman Gill",
    role: "Batsman",
    number: 77,
    country: "India",
    group: "Group B",
    stats: {
      ODI: { runs: 2800, average: 48.3, strikeRate: 95.2, wickets: 0, economy: 0, catches: 14 },
      T20: { runs: 1950, average: 42.1, strikeRate: 138.5, wickets: 0, economy: 0, catches: 11 },
      Test: { runs: 3100, average: 43.2, strikeRate: 56.5, wickets: 0, economy: 0, catches: 15 },
    },
    strengths: ["Technique", "Stroke play", "Opening", "Consistency"],
    weaknesses: ["Pace bowling", "Short balls", "Variable bounce"],
    form: "Excellent",
    recentForm: [92, 88, 85, 91, 89],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "ruturaj",
    name: "Ruturaj Gaikwad",
    role: "Batsman",
    number: 23,
    country: "India",
    group: "Group B",
    stats: {
      ODI: { runs: 1200, average: 42.8, strikeRate: 98.5, wickets: 0, economy: 0, catches: 8 },
      T20: { runs: 2100, average: 39.6, strikeRate: 141.2, wickets: 0, economy: 0, catches: 9 },
      Test: { runs: 850, average: 38.2, strikeRate: 52.3, wickets: 0, economy: 0, catches: 5 },
    },
    strengths: ["T20 batting", "Aggressive play", "Strike rotation", "Consistency"],
    weaknesses: ["Pace bowling", "Bounce", "Test experience"],
    form: "Excellent",
    recentForm: [85, 88, 92, 79, 87],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "kl-rahul",
    name: "KL Rahul",
    role: "Batsman",
    number: 1,
    country: "India",
    group: "Group B",
    stats: {
      ODI: { runs: 3100, average: 45.2, strikeRate: 87.5, wickets: 0, economy: 0, catches: 16 },
      T20: { runs: 1500, average: 39.5, strikeRate: 132.1, wickets: 0, economy: 0, catches: 10 },
      Test: { runs: 2400, average: 40.1, strikeRate: 54.8, wickets: 0, economy: 0, catches: 12 },
    },
    strengths: ["Opening play", "Technique", "Consistency", "Leadership"],
    weaknesses: ["Short balls", "Aggressive pace", "T20 tempo"],
    form: "Average",
    recentForm: [65, 72, 68, 75, 70],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "shreyas",
    name: "Shreyas Iyer",
    role: "Batsman",
    number: 21,
    country: "India",
    group: "Group B",
    stats: {
      ODI: { runs: 1850, average: 44.0, strikeRate: 96.3, wickets: 0, economy: 0, catches: 9 },
      T20: { runs: 2250, average: 38.5, strikeRate: 139.8, wickets: 0, economy: 0, catches: 12 },
      Test: { runs: 950, average: 39.6, strikeRate: 55.2, wickets: 0, economy: 0, catches: 7 },
    },
    strengths: ["Middle order", "Technique", "T20 batting", "Strike rotation"],
    weaknesses: ["Pace bowling", "Short balls", "Test experience"],
    form: "Good",
    recentForm: [78, 82, 75, 88, 80],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "suryakumar",
    name: "Suryakumar Yadav",
    role: "Batsman",
    number: 63,
    country: "India",
    group: "Group B",
    stats: {
      ODI: { runs: 950, average: 38.0, strikeRate: 102.3, wickets: 0, economy: 0, catches: 6 },
      T20: { runs: 3200, average: 42.5, strikeRate: 145.2, wickets: 0, economy: 0, catches: 14 },
      Test: { runs: 400, average: 35.2, strikeRate: 58.1, wickets: 0, economy: 0, catches: 2 },
    },
    strengths: ["T20 batting", "Innovative shots", "Unorthodox play", "Strike rotation"],
    weaknesses: ["Pace bowling", "Conventional technique", "Test format"],
    form: "Excellent",
    recentForm: [88, 92, 85, 90, 87],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "hardik",
    name: "Hardik Pandya",
    role: "All-rounder",
    number: 33,
    country: "India",
    group: "Group B",
    stats: {
      ODI: { runs: 1100, average: 32.5, strikeRate: 108.2, wickets: 68, economy: 6.2, catches: 12 },
      T20: { runs: 1950, average: 38.1, strikeRate: 142.3, wickets: 95, economy: 8.5, catches: 15 },
      Test: { runs: 680, average: 28.3, strikeRate: 61.2, wickets: 32, economy: 4.1, catches: 8 },
    },
    strengths: ["Explosive batting", "Pace bowling", "Death bowling", "All-round capability"],
    weaknesses: ["Injury prone", "Consistency", "Spin bowling"],
    form: "Good",
    recentForm: [75, 82, 88, 71, 80],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "axar",
    name: "Axar Patel",
    role: "All-rounder",
    number: 78,
    country: "India",
    group: "Group B",
    stats: {
      ODI: { runs: 550, average: 36.7, strikeRate: 95.2, wickets: 48, economy: 5.8, catches: 8 },
      T20: { runs: 780, average: 34.2, strikeRate: 128.1, wickets: 52, economy: 8.2, catches: 10 },
      Test: { runs: 620, average: 31.0, strikeRate: 52.8, wickets: 42, economy: 3.5, catches: 12 },
    },
    strengths: ["Left-arm spin", "Batting all-rounder", "Variations", "Death bowling"],
    weaknesses: ["Pace bowling", "Opening overs", "Consistency"],
    form: "Good",
    recentForm: [72, 78, 82, 75, 80],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "kuldeep",
    name: "Kuldeep Yadav",
    role: "Bowler",
    number: 66,
    country: "India",
    group: "Group B",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 65, economy: 5.6, catches: 8 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 78, economy: 7.8, catches: 6 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 68, economy: 3.2, catches: 5 },
    },
    strengths: ["Left-arm wrist spin", "Variations", "Death bowling", "T20 bowling"],
    weaknesses: ["Pace bowling", "Accuracy", "Consistency"],
    form: "Average",
    recentForm: [65, 72, 68, 75, 70],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "mohammedsiraj",
    name: "Mohammed Siraj",
    role: "Bowler",
    number: 62,
    country: "India",
    group: "Group B",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 35, economy: 5.8, catches: 4 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 42, economy: 8.1, catches: 3 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 45, economy: 3.4, catches: 2 },
    },
    strengths: ["Fast bowling", "Death bowling", "Aggression", "Yorkers"],
    weaknesses: ["Swing bowling", "Accuracy", "Consistency"],
    form: "Good",
    recentForm: [75, 80, 78, 72, 82],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "arshdeep",
    name: "Arshdeep Singh",
    role: "Bowler",
    number: 91,
    country: "India",
    group: "Group B",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 28, economy: 6.2, catches: 2 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 52, economy: 8.5, catches: 4 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 18, economy: 3.8, catches: 1 },
    },
    strengths: ["Death bowling", "Left-arm pace", "Yorkers", "T20 expertise"],
    weaknesses: ["Opening overs", "Accuracy", "Test experience"],
    form: "Excellent",
    recentForm: [82, 88, 85, 90, 87],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "varun-chakravarthy",
    name: "Varun Chakravarthy",
    role: "Bowler",
    number: 88,
    country: "India",
    group: "Group B",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 22, economy: 6.8, catches: 2 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 48, economy: 8.2, catches: 5 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 15, economy: 3.9, catches: 1 },
    },
    strengths: ["Mystery spin", "Variations", "T20 bowling", "Googly"],
    weaknesses: ["Accuracy", "Pace bowling", "Test format"],
    form: "Good",
    recentForm: [72, 78, 75, 80, 77],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "ravi-bishnoi",
    name: "Ravi Bishnoi",
    role: "Bowler",
    number: 86,
    country: "India",
    group: "Group B",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 18, economy: 5.9, catches: 1 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 62, economy: 7.6, catches: 6 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 12, economy: 3.6, catches: 2 },
    },
    strengths: ["Leg-spin", "Variations", "T20 bowling", "Googly"],
    weaknesses: ["Pace bowling", "Accuracy", "Test experience"],
    form: "Excellent",
    recentForm: [85, 88, 92, 80, 89],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },

  // GROUP C - EMERGING PLAYERS
  {
    id: "yashasvi",
    name: "Yashasvi Jaiswal",
    role: "Batsman",
    number: 39,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 500, average: 41.7, strikeRate: 88.2, wickets: 0, economy: 0, catches: 3 },
      T20: { runs: 1200, average: 38.7, strikeRate: 126.3, wickets: 0, economy: 0, catches: 6 },
      Test: { runs: 2100, average: 42.0, strikeRate: 52.5, wickets: 0, economy: 0, catches: 8 },
    },
    strengths: ["Test batting", "Technique", "Concentration", "Opening"],
    weaknesses: ["T20 experience", "Pace bowling", "Pressure situations"],
    form: "Excellent",
    recentForm: [88, 92, 85, 79, 91],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "tilak-varma",
    name: "Tilak Varma",
    role: "Batsman",
    number: 41,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 320, average: 35.2, strikeRate: 92.0, wickets: 0, economy: 0, catches: 2 },
      T20: { runs: 1650, average: 38.1, strikeRate: 136.7, wickets: 0, economy: 0, catches: 8 },
      Test: { runs: 450, average: 32.1, strikeRate: 48.2, wickets: 0, economy: 0, catches: 3 },
    },
    strengths: ["T20 batting", "Strike rotation", "Aggressive play", "Youth"],
    weaknesses: ["Pace bowling", "Short balls", "Test experience"],
    form: "Good",
    recentForm: [75, 80, 82, 78, 85],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "abhishek-sharma",
    name: "Abhishek Sharma",
    role: "Batsman",
    number: 87,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 280, average: 35.0, strikeRate: 105.2, wickets: 0, economy: 0, catches: 2 },
      T20: { runs: 1200, average: 36.4, strikeRate: 142.9, wickets: 0, economy: 0, catches: 5 },
      Test: { runs: 180, average: 30.0, strikeRate: 54.5, wickets: 0, economy: 0, catches: 1 },
    },
    strengths: ["Aggressive batting", "T20 play", "Youth", "Innovative shots"],
    weaknesses: ["Pace bowling", "Consistency", "Test experience"],
    form: "Good",
    recentForm: [72, 78, 75, 82, 80],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "ishan-kishan",
    name: "Ishan Kishan",
    role: "Wicket-keeper",
    number: 24,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 620, average: 38.8, strikeRate: 110.2, wickets: 0, economy: 0, catches: 12 },
      T20: { runs: 1800, average: 37.5, strikeRate: 138.5, wickets: 0, economy: 0, catches: 18 },
      Test: { runs: 450, average: 32.1, strikeRate: 55.2, wickets: 0, economy: 0, catches: 8 },
    },
    strengths: ["Wicket-keeping", "Aggressive batting", "T20 skills", "Left-hander"],
    weaknesses: ["Pace bowling", "Consistency", "Test batting"],
    form: "Average",
    recentForm: [65, 72, 70, 75, 68],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "sanju-samson",
    name: "Sanju Samson",
    role: "Wicket-keeper",
    number: 25,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 540, average: 36.0, strikeRate: 105.8, wickets: 0, economy: 0, catches: 10 },
      T20: { runs: 1950, average: 39.0, strikeRate: 140.2, wickets: 0, economy: 0, catches: 15 },
      Test: { runs: 320, average: 28.6, strikeRate: 52.3, wickets: 0, economy: 0, catches: 6 },
    },
    strengths: ["Wicket-keeping", "T20 batting", "Aggression", "Strike rotation"],
    weaknesses: ["Pace bowling", "Consistency", "Test experience"],
    form: "Good",
    recentForm: [78, 82, 80, 85, 83],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "rinku-singh",
    name: "Rinku Singh",
    role: "Batsman",
    number: 32,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 180, average: 32.0, strikeRate: 108.4, wickets: 0, economy: 0, catches: 1 },
      T20: { runs: 1400, average: 37.3, strikeRate: 141.5, wickets: 0, economy: 0, catches: 7 },
      Test: { runs: 240, average: 30.0, strikeRate: 50.8, wickets: 0, economy: 0, catches: 2 },
    },
    strengths: ["T20 batting", "Strike rotation", "Death hitting", "Aggression"],
    weaknesses: ["Pace bowling", "Test format", "Consistency"],
    form: "Good",
    recentForm: [75, 80, 78, 82, 79],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "nitish-reddy",
    name: "Nitish Kumar Reddy",
    role: "All-rounder",
    number: 74,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 800, average: 36.4, strikeRate: 110.2, wickets: 28, economy: 5.8, catches: 7 },
      T20: { runs: 1100, average: 42.3, strikeRate: 142.5, wickets: 35, economy: 8.2, catches: 10 },
      Test: { runs: 1300, average: 38.2, strikeRate: 62.5, wickets: 42, economy: 3.5, catches: 9 },
    },
    strengths: ["Explosive batting", "Pace bowling", "All-round capabilities", "T20 skills"],
    weaknesses: ["Spin bowling", "Test consistency", "Against left-arm pace"],
    form: "Excellent",
    recentForm: [85, 88, 92, 78, 90],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "dhruv-jurel",
    name: "Dhruv Jurel",
    role: "Wicket-keeper",
    number: 95,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 280, average: 35.0, strikeRate: 87.5, wickets: 0, economy: 0, catches: 8 },
      T20: { runs: 650, average: 32.5, strikeRate: 125.4, wickets: 0, economy: 0, catches: 10 },
      Test: { runs: 950, average: 38.0, strikeRate: 53.2, wickets: 0, economy: 0, catches: 18 },
    },
    strengths: ["Wicket-keeping", "Test batting", "Technique", "Concentration"],
    weaknesses: ["Pace bowling", "T20 experience", "Aggression"],
    form: "Good",
    recentForm: [72, 78, 82, 75, 80],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "rajat-patidar",
    name: "Rajat Patidar",
    role: "Batsman",
    number: 82,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 150, average: 30.0, strikeRate: 95.2, wickets: 0, economy: 0, catches: 1 },
      T20: { runs: 800, average: 34.8, strikeRate: 132.2, wickets: 0, economy: 0, catches: 4 },
      Test: { runs: 320, average: 32.0, strikeRate: 49.5, wickets: 0, economy: 0, catches: 2 },
    },
    strengths: ["T20 batting", "Strike rotation", "Domestic success", "Youth"],
    weaknesses: ["Pace bowling", "International experience", "Test format"],
    form: "Average",
    recentForm: [65, 72, 68, 75, 70],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "sarfaraz-khan",
    name: "Sarfaraz Khan",
    role: "Batsman",
    number: 42,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 220, average: 31.4, strikeRate: 96.5, wickets: 0, economy: 0, catches: 2 },
      T20: { runs: 950, average: 35.2, strikeRate: 139.6, wickets: 0, economy: 0, catches: 5 },
      Test: { runs: 680, average: 34.0, strikeRate: 51.2, wickets: 0, economy: 0, catches: 4 },
    },
    strengths: ["Aggressive batting", "Potential", "Youth", "Domestic cricket"],
    weaknesses: ["Pace bowling", "International experience", "Consistency"],
    form: "Good",
    recentForm: [72, 78, 75, 82, 80],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "shivam-dube",
    name: "Shivam Dube",
    role: "All-rounder",
    number: 40,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 640, average: 32.0, strikeRate: 102.4, wickets: 15, economy: 6.5, catches: 5 },
      T20: { runs: 1280, average: 36.0, strikeRate: 140.1, wickets: 28, economy: 8.8, catches: 8 },
      Test: { runs: 420, average: 30.0, strikeRate: 55.3, wickets: 8, economy: 4.2, catches: 3 },
    },
    strengths: ["Aggressive batting", "Left-arm pace", "All-round capability", "T20 skills"],
    weaknesses: ["Consistency", "Fielding", "Test format"],
    form: "Average",
    recentForm: [68, 75, 70, 78, 72],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "washington",
    name: "Washington Sundar",
    role: "All-rounder",
    number: 31,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 600, average: 35.3, strikeRate: 88.2, wickets: 32, economy: 5.1, catches: 5 },
      T20: { runs: 850, average: 33.5, strikeRate: 128.8, wickets: 38, economy: 7.9, catches: 7 },
      Test: { runs: 950, average: 32.1, strikeRate: 58.5, wickets: 48, economy: 3.2, catches: 8 },
    },
    strengths: ["Left-arm spin", "Batting all-rounder", "Variations", "T20 bowling"],
    weaknesses: ["Pace bowling", "Consistency", "Experience"],
    form: "Average",
    recentForm: [65, 68, 72, 60, 70],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "prasidh-krishna",
    name: "Prasidh Krishna",
    role: "Bowler",
    number: 89,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 12, economy: 6.8, catches: 1 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 28, economy: 9.2, catches: 2 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 22, economy: 3.6, catches: 1 },
    },
    strengths: ["Fast bowling", "Bounce", "Pace", "Yorkers"],
    weaknesses: ["Accuracy", "Consistency", "Experience"],
    form: "Average",
    recentForm: [65, 72, 68, 75, 70],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "akash-deep",
    name: "Akash Deep",
    role: "Bowler",
    number: 94,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 8, economy: 6.5, catches: 0 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 15, economy: 8.8, catches: 1 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 18, economy: 3.8, catches: 2 },
    },
    strengths: ["Fast bowling", "Bounce", "Pace", "Test potential"],
    weaknesses: ["Accuracy", "Experience", "Death bowling"],
    form: "Good",
    recentForm: [72, 75, 78, 70, 76],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "mukesh-kumar",
    name: "Mukesh Kumar",
    role: "Bowler",
    number: 90,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 5, economy: 6.2, catches: 1 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 12, economy: 8.5, catches: 1 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 25, economy: 3.4, catches: 2 },
    },
    strengths: ["Fast bowling", "Swing", "Test cricket", "Accuracy"],
    weaknesses: ["Consistency", "Death overs", "Experience"],
    form: "Good",
    recentForm: [70, 75, 78, 72, 76],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "harshit-rana",
    name: "Harshit Rana",
    role: "Bowler",
    number: 97,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 6, economy: 6.8, catches: 0 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 18, economy: 8.9, catches: 2 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 20, economy: 3.7, catches: 1 },
    },
    strengths: ["Fast bowling", "Pace", "Youth", "Potential"],
    weaknesses: ["Consistency", "Experience", "Accuracy"],
    form: "Good",
    recentForm: [72, 76, 74, 78, 75],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "yuzvendra-chahal",
    name: "Yuzvendra Chahal",
    role: "Bowler",
    number: 72,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 95, economy: 5.8, catches: 8 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 142, economy: 7.9, catches: 12 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 8, economy: 4.1, catches: 1 },
    },
    strengths: ["Leg-spin", "Variations", "T20 bowling", "Googly"],
    weaknesses: ["Pace bowling", "Consistency", "Test format"],
    form: "Good",
    recentForm: [75, 80, 78, 82, 79],
    formatAvailability: { ODI: true, T20: true, Test: false },
  },
  {
    id: "deepak-chahar",
    name: "Deepak Chahar",
    role: "Bowler",
    number: 68,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 32, economy: 5.9, catches: 3 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 45, economy: 8.4, catches: 4 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 12, economy: 3.9, catches: 1 },
    },
    strengths: ["Swing bowling", "Death bowling", "Yorkers", "Variations"],
    weaknesses: ["Consistency", "Pace bowling", "Experience"],
    form: "Average",
    recentForm: [68, 72, 70, 75, 71],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "umran-malik",
    name: "Umran Malik",
    role: "Bowler",
    number: 84,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 8, economy: 7.2, catches: 0 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 35, economy: 9.1, catches: 2 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 10, economy: 4.2, catches: 1 },
    },
    strengths: ["Pace", "Raw pace", "Bounce", "Youth"],
    weaknesses: ["Accuracy", "Control", "Consistency"],
    form: "Average",
    recentForm: [65, 70, 68, 72, 69],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "navdeep-saini",
    name: "Navdeep Saini",
    role: "Bowler",
    number: 85,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 15, economy: 6.1, catches: 2 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 32, economy: 8.6, catches: 3 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 8, economy: 3.8, catches: 1 },
    },
    strengths: ["Fast bowling", "Bounce", "Pace", "Yorkers"],
    weaknesses: ["Consistency", "Accuracy", "Experience"],
    form: "Good",
    recentForm: [70, 75, 72, 78, 74],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "shardul-thakur",
    name: "Shardul Thakur",
    role: "All-rounder",
    number: 71,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 280, average: 28.0, strikeRate: 89.2, wickets: 25, economy: 6.2, catches: 4 },
      T20: { runs: 420, average: 30.0, strikeRate: 120.7, wickets: 32, economy: 8.9, catches: 6 },
      Test: { runs: 520, average: 26.0, strikeRate: 48.5, wickets: 45, economy: 3.6, catches: 8 },
    },
    strengths: ["All-rounder", "Death bowling", "Batting ability", "Experience"],
    weaknesses: ["Consistency", "Pace bowling", "Spin"],
    form: "Average",
    recentForm: [65, 70, 72, 68, 71],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "avesh-khan",
    name: "Avesh Khan",
    role: "Bowler",
    number: 92,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 10, economy: 6.8, catches: 1 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 38, economy: 8.7, catches: 3 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 6, economy: 4.1, catches: 1 },
    },
    strengths: ["Fast bowling", "Death bowling", "Yorkers", "Pace"],
    weaknesses: ["Accuracy", "Consistency", "Experience"],
    form: "Good",
    recentForm: [72, 78, 75, 80, 77],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "mayank-yadav",
    name: "Mayank Yadav",
    role: "Bowler",
    number: 98,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 4, economy: 7.0, catches: 0 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 12, economy: 9.0, catches: 1 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 5, economy: 4.0, catches: 1 },
    },
    strengths: ["Pace", "Bounce", "Potential", "Youth"],
    weaknesses: ["Accuracy", "Experience", "Consistency"],
    form: "Average",
    recentForm: [62, 68, 65, 70, 67],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "chetan-sakariya",
    name: "Chetan Sakariya",
    role: "Bowler",
    number: 96,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 6, economy: 6.5, catches: 0 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 22, economy: 8.8, catches: 2 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 8, economy: 3.7, catches: 1 },
    },
    strengths: ["Left-arm pace", "Death bowling", "Yorkers", "Youth"],
    weaknesses: ["Accuracy", "Consistency", "Experience"],
    form: "Average",
    recentForm: [65, 70, 68, 72, 69],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "riyan-parag",
    name: "Riyan Parag",
    role: "All-rounder",
    number: 44,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 150, average: 30.0, strikeRate: 100.0, wickets: 5, economy: 7.0, catches: 2 },
      T20: { runs: 780, average: 34.8, strikeRate: 138.1, wickets: 18, economy: 8.9, catches: 5 },
      Test: { runs: 200, average: 25.0, strikeRate: 50.5, wickets: 3, economy: 4.5, catches: 2 },
    },
    strengths: ["T20 batting", "Aggressive play", "Off-spin", "Youth"],
    weaknesses: ["Consistency", "Test experience", "Pace bowling"],
    form: "Good",
    recentForm: [70, 75, 72, 78, 74],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "prithvi-shaw",
    name: "Prithvi Shaw",
    role: "Batsman",
    number: 22,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 180, average: 30.0, strikeRate: 98.4, wickets: 0, economy: 0, catches: 2 },
      T20: { runs: 920, average: 35.4, strikeRate: 141.5, wickets: 0, economy: 0, catches: 4 },
      Test: { runs: 1320, average: 36.7, strikeRate: 54.2, wickets: 0, economy: 0, catches: 6 },
    },
    strengths: ["Test opening", "Aggressive batting", "Technique", "Opening"],
    weaknesses: ["Pace bowling", "Short balls", "Consistency"],
    form: "Average",
    recentForm: [65, 72, 68, 75, 70],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "sai-sudharsan",
    name: "Sai Sudharsan",
    role: "Batsman",
    number: 43,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 240, average: 34.3, strikeRate: 94.1, wickets: 0, economy: 0, catches: 2 },
      T20: { runs: 680, average: 33.2, strikeRate: 128.3, wickets: 0, economy: 0, catches: 4 },
      Test: { runs: 850, average: 35.4, strikeRate: 52.1, wickets: 0, economy: 0, catches: 5 },
    },
    strengths: ["Test batting", "Technique", "Concentration", "Youth"],
    weaknesses: ["Pace bowling", "T20 experience", "International cricket"],
    form: "Good",
    recentForm: [72, 78, 75, 82, 80],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "abhimanyu-easwaran",
    name: "Abhimanyu Easwaran",
    role: "Batsman",
    number: 46,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 120, average: 28.0, strikeRate: 85.7, wickets: 0, economy: 0, catches: 1 },
      T20: { runs: 380, average: 28.5, strikeRate: 120.0, wickets: 0, economy: 0, catches: 2 },
      Test: { runs: 1200, average: 36.4, strikeRate: 50.2, wickets: 0, economy: 0, catches: 8 },
    },
    strengths: ["Test cricket", "Opening", "Technique", "Concentration"],
    weaknesses: ["Pace bowling", "T20 experience", "Consistency"],
    form: "Average",
    recentForm: [68, 72, 70, 75, 71],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "yash-thakur",
    name: "Yash Thakur",
    role: "Bowler",
    number: 100,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 2, economy: 6.8, catches: 0 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 8, economy: 8.9, catches: 1 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 3, economy: 4.2, catches: 0 },
    },
    strengths: ["Fast bowling", "Pace", "Potential", "Youth"],
    weaknesses: ["Accuracy", "Experience", "Consistency"],
    form: "Average",
    recentForm: [60, 65, 62, 68, 64],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "sai-kishore",
    name: "Sai Kishore",
    role: "Bowler",
    number: 101,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 4, economy: 6.2, catches: 1 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 12, economy: 8.1, catches: 2 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 5, economy: 3.8, catches: 1 },
    },
    strengths: ["Left-arm spin", "Variations", "Potential", "Youth"],
    weaknesses: ["Consistency", "Experience", "Pace bowling"],
    form: "Good",
    recentForm: [68, 72, 70, 75, 71],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "ishan-porel",
    name: "Ishan Porel",
    role: "Bowler",
    number: 102,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 0, average: 0, strikeRate: 0, wickets: 3, economy: 6.8, catches: 0 },
      T20: { runs: 0, average: 0, strikeRate: 0, wickets: 6, economy: 8.7, catches: 0 },
      Test: { runs: 0, average: 0, strikeRate: 0, wickets: 8, economy: 3.9, catches: 1 },
    },
    strengths: ["Fast bowling", "Pace", "Bounce", "Potential"],
    weaknesses: ["Accuracy", "Experience", "Consistency"],
    form: "Average",
    recentForm: [62, 68, 65, 70, 67],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
  {
    id: "rajamani-krishnan",
    name: "Rajeev Ram Singh",
    role: "Batsman",
    number: 47,
    country: "India",
    group: "Group C",
    stats: {
      ODI: { runs: 100, average: 25.0, strikeRate: 90.0, wickets: 0, economy: 0, catches: 1 },
      T20: { runs: 420, average: 30.0, strikeRate: 125.4, wickets: 0, economy: 0, catches: 3 },
      Test: { runs: 680, average: 32.0, strikeRate: 52.3, wickets: 0, economy: 0, catches: 4 },
    },
    strengths: ["Domestic cricket", "Domestic success", "Potential", "Youth"],
    weaknesses: ["Pace bowling", "International experience", "Consistency"],
    form: "Average",
    recentForm: [60, 68, 65, 72, 68],
    formatAvailability: { ODI: true, T20: true, Test: true },
  },
]

export const oppositionTeams = {
  Australia: [
    {
      name: "Steve Smith",
      role: "Batsman" as Role,
      strengths: ["Technique", "Consistency", "Placement"],
      weaknesses: ["Spin", "Short ball", "Bounce"],
      recentForm: [78, 92, 65, 88, 71],
    },
    {
      name: "David Warner",
      role: "Batsman" as Role,
      strengths: ["Aggression", "Pace play", "Opening"],
      weaknesses: ["Spin", "Yorkers", "Length"],
      recentForm: [45, 72, 88, 51, 75],
    },
    {
      name: "Marnus Labuschagne",
      role: "Batsman" as Role,
      strengths: ["Defense", "Test cricket", "Concentration"],
      weaknesses: ["Pace", "Aggressive bowling"],
      recentForm: [65, 78, 82, 45, 71],
    },
    {
      name: "Travis Head",
      role: "Batsman" as Role,
      strengths: ["Aggressive batting", "T20 play", "Pace hitting"],
      weaknesses: ["Spin", "Yorkers"],
      recentForm: [88, 52, 71, 65, 79],
    },
    {
      name: "Glenn Maxwell",
      role: "All-rounder" as Role,
      strengths: ["T20 batting", "Explosive", "Variation"],
      weaknesses: ["Length balls", "Pace"],
      recentForm: [72, 85, 48, 91, 61],
    },
    {
      name: "Josh Hazlewood",
      role: "Bowler" as Role,
      strengths: ["Line bowling", "Consistency", "Test cricket"],
      weaknesses: ["Death overs", "Short pitch"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Pat Cummins",
      role: "Bowler" as Role,
      strengths: ["Pace", "Yorkers", "Aggression"],
      weaknesses: ["Bounce", "Spin"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Mitchell Starc",
      role: "Bowler" as Role,
      strengths: ["Swing", "Pace", "Death bowling"],
      weaknesses: ["Control", "Consistency"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Nathan Lyon",
      role: "Bowler" as Role,
      strengths: ["Off-spin", "Experience", "Consistency"],
      weaknesses: ["Pace", "Short ball"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Mitchell Marsh",
      role: "All-rounder" as Role,
      strengths: ["All-round", "Pace bowling", "Batting"],
      weaknesses: ["Injury", "Spin"],
      recentForm: [45, 62, 78, 38, 55],
    },
    {
      name: "Adam Zampa",
      role: "Bowler" as Role,
      strengths: ["Leg-spin", "Variation", "T20"],
      weaknesses: ["Pace", "Full length"],
      recentForm: [0, 0, 0, 0, 0],
    },
  ],
  "South Africa": [
    {
      name: "Temba Bavuma",
      role: "Batsman" as Role,
      strengths: ["Technique", "Short balls", "Test craft"],
      weaknesses: ["Pace", "Length balls"],
      recentForm: [62, 48, 71, 82, 55],
    },
    {
      name: "Reeza Hendricks",
      role: "Batsman" as Role,
      strengths: ["Opening", "Pace play", "Consistency"],
      weaknesses: ["Spin", "Movement"],
      recentForm: [78, 65, 88, 42, 79],
    },
    {
      name: "Aiden Markram",
      role: "Batsman" as Role,
      strengths: ["Technique", "Test batting", "Aggression"],
      weaknesses: ["Bounce", "Pace"],
      recentForm: [71, 85, 62, 88, 74],
    },
    {
      name: "David Miller",
      role: "Batsman" as Role,
      strengths: ["Aggressive batting", "T20 play", "Experience"],
      weaknesses: ["Spin", "Yorkers"],
      recentForm: [65, 72, 88, 51, 79],
    },
    {
      name: "Andile Phehlukwayo",
      role: "All-rounder" as Role,
      strengths: ["All-around", "Death bowling", "Batting"],
      weaknesses: ["Pace", "Consistency"],
      recentForm: [52, 68, 45, 61, 58],
    },
    {
      name: "Kagiso Rabada",
      role: "Bowler" as Role,
      strengths: ["Pace", "Swing", "Aggression"],
      weaknesses: ["Death bowling", "Control"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Anrich Nortje",
      role: "Bowler" as Role,
      strengths: ["Short ball", "Pace", "Bounce"],
      weaknesses: ["Yorkers", "Control"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Tabraiz Shamsi",
      role: "Bowler" as Role,
      strengths: ["Leg-spin", "Variation", "Experience"],
      weaknesses: ["Pace", "Short ball"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Ottneil Baartman",
      role: "Bowler" as Role,
      strengths: ["Pace", "Bounce", "Short pitch"],
      weaknesses: ["Length", "Control"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Keshav Maharaj",
      role: "Bowler" as Role,
      strengths: ["Left-arm spin", "Test bowling", "Consistency"],
      weaknesses: ["Pace", "Short ball"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Jonathan Bird",
      role: "Bowler" as Role,
      strengths: ["Pace", "Accuracy", "Variation"],
      weaknesses: ["Bounce", "Experience"],
      recentForm: [0, 0, 0, 0, 0],
    },
  ],
  Pakistan: [
    {
      name: "Babar Azam",
      role: "Batsman" as Role,
      strengths: ["Technique", "Consistency", "Leadership"],
      weaknesses: ["Short ball", "Yorkers"],
      recentForm: [88, 71, 92, 65, 79],
    },
    {
      name: "Fakhar Zaman",
      role: "Batsman" as Role,
      strengths: ["Aggression", "Pace play", "Opening"],
      weaknesses: ["Spin", "Short balls"],
      recentForm: [72, 45, 82, 68, 51],
    },
    {
      name: "Azhar Ali",
      role: "Batsman" as Role,
      strengths: ["Defense", "Test cricket", "Experience"],
      weaknesses: ["Pace", "Bounce"],
      recentForm: [58, 72, 65, 48, 62],
    },
    {
      name: "Haider Ali",
      role: "Batsman" as Role,
      strengths: ["Aggression", "T20 batting", "Speed"],
      weaknesses: ["Patience", "Length balls"],
      recentForm: [65, 82, 71, 48, 75],
    },
    {
      name: "Iftikhar Ahmed",
      role: "All-rounder" as Role,
      strengths: ["Aggressive batting", "Medium pace", "Death hitting"],
      weaknesses: ["Consistency", "Spin"],
      recentForm: [45, 68, 52, 78, 61],
    },
    {
      name: "Shaheen Afridi",
      role: "Bowler" as Role,
      strengths: ["Swing", "Pace", "Left-arm angle"],
      weaknesses: ["Death bowling", "Variations"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Naseem Shah",
      role: "Bowler" as Role,
      strengths: ["Short ball", "Pace", "Bounce"],
      weaknesses: ["Length bowling", "Experience"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Haris Rauf",
      role: "Bowler" as Role,
      strengths: ["Pace", "Death bowling", "Yorkers"],
      weaknesses: ["Length", "Control"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Shadab Khan",
      role: "All-rounder" as Role,
      strengths: ["Leg-spin", "Batting", "T20 bowling"],
      weaknesses: ["Pace", "Consistency"],
      recentForm: [52, 68, 45, 72, 58],
    },
    {
      name: "Mohammad Hasnain",
      role: "Bowler" as Role,
      strengths: ["Pace", "Bounce", "Death bowling"],
      weaknesses: ["Control", "Experience"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Maqbool Ahmed",
      role: "Batsman" as Role,
      strengths: ["Test batting", "Defense", "Concentration"],
      weaknesses: ["Pace", "Aggressive bowling"],
      recentForm: [68, 72, 58, 45, 71],
    },
  ],
  "New Zealand": [
    {
      name: "Kane Williamson",
      role: "Batsman" as Role,
      strengths: ["Technique", "All-format play", "Experience"],
      weaknesses: ["Pace", "Short ball"],
      recentForm: [85, 72, 68, 91, 76],
    },
    {
      name: "Tom Latham",
      role: "Wicket-keeper" as Role,
      strengths: ["Defense", "Technique", "Test cricket"],
      weaknesses: ["Pace", "Bounce"],
      recentForm: [71, 82, 58, 75, 68],
    },
    {
      name: "Devon Conway",
      role: "Batsman" as Role,
      strengths: ["Technique", "Concentration", "Opening"],
      weaknesses: ["Aggressive bowling", "Short ball"],
      recentForm: [78, 65, 88, 71, 82],
    },
    {
      name: "Henry Nicholls",
      role: "Batsman" as Role,
      strengths: ["Left-hand batting", "Test cricket", "Defensive"],
      weaknesses: ["Pace", "Yorkers"],
      recentForm: [62, 75, 58, 68, 71],
    },
    {
      name: "Glenn Phillips",
      role: "All-rounder" as Role,
      strengths: ["T20 batting", "Aggression", "Variation"],
      weaknesses: ["Pace", "Spin"],
      recentForm: [68, 82, 71, 48, 79],
    },
    {
      name: "Tim Southee",
      role: "Bowler" as Role,
      strengths: ["Swing", "New ball", "Experience"],
      weaknesses: ["Death bowling", "Bounce"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Trent Boult",
      role: "Bowler" as Role,
      strengths: ["Swing", "Pace", "Left-arm angle"],
      weaknesses: ["Yorkers", "Death"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Kyle Jamieson",
      role: "All-rounder" as Role,
      strengths: ["Bounce", "All-around", "Pace"],
      weaknesses: ["Length", "Spin"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Lockie Ferguson",
      role: "Bowler" as Role,
      strengths: ["Pace", "Bounce", "Death bowling"],
      weaknesses: ["Control", "Experience"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Mitch Santner",
      role: "All-rounder" as Role,
      strengths: ["Left-arm spin", "Batting", "All-around"],
      weaknesses: ["Pace", "Short ball"],
      recentForm: [52, 62, 48, 65, 58],
    },
    {
      name: "Neil Wagner",
      role: "Bowler" as Role,
      strengths: ["Short ball", "Pace", "Test cricket"],
      weaknesses: ["Length", "Death overs"],
      recentForm: [0, 0, 0, 0, 0],
    },
  ],
  England: [
    {
      name: "Joe Root",
      role: "Batsman" as Role,
      strengths: ["Technique", "Versatility", "Test batting"],
      weaknesses: ["Short ball", "Yorkers"],
      recentForm: [78, 65, 88, 72, 81],
    },
    {
      name: "Ben Stokes",
      role: "All-rounder" as Role,
      strengths: ["All-rounder", "Aggressive", "Experience"],
      weaknesses: ["Consistency", "Short pitch"],
      recentForm: [75, 82, 68, 79, 71],
    },
    {
      name: "Jofra Archer",
      role: "Bowler" as Role,
      strengths: ["Pace", "Yorkers", "Death bowling"],
      weaknesses: ["Control", "Consistency"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Phil Salt",
      role: "Batsman" as Role,
      strengths: ["Aggressive", "T20 batting", "Pace play"],
      weaknesses: ["Spin", "Short ball"],
      recentForm: [71, 88, 65, 82, 76],
    },
    {
      name: "Harry Brook",
      role: "Batsman" as Role,
      strengths: ["Technique", "Test batting", "Aggression"],
      weaknesses: ["Bounce", "Fast bowling"],
      recentForm: [82, 76, 88, 71, 79],
    },
    {
      name: "Olly Stone",
      role: "Bowler" as Role,
      strengths: ["Pace", "Accuracy", "Swing"],
      weaknesses: ["Death overs", "Bounce"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Mark Wood",
      role: "Bowler" as Role,
      strengths: ["Pace", "Bounce", "Pace attack"],
      weaknesses: ["Control", "Injury"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Reece Topley",
      role: "Bowler" as Role,
      strengths: ["Left-arm pace", "Swing", "Experience"],
      weaknesses: ["Death bowling", "Consistency"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Jacob Bethell",
      role: "Batsman" as Role,
      strengths: ["Youth", "Potential", "Aggressive play"],
      weaknesses: ["Experience", "Pace bowling"],
      recentForm: [65, 72, 58, 68, 62],
    },
    {
      name: "Adil Rashid",
      role: "Bowler" as Role,
      strengths: ["Leg-spin", "Variation", "T20 expertise"],
      weaknesses: ["Pace", "Short ball"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Liam Livingstone",
      role: "All-rounder" as Role,
      strengths: ["Aggressive", "All-rounder", "Variation"],
      weaknesses: ["Pace", "Spin"],
      recentForm: [68, 75, 82, 61, 79],
    },
  ],
  "Sri Lanka": [
    {
      name: "Kusal Perera",
      role: "Batsman" as Role,
      strengths: ["Aggression", "Pace play", "T20 batting"],
      weaknesses: ["Spin", "Short balls"],
      recentForm: [72, 58, 65, 79, 68],
    },
    {
      name: "Dhananjaya de Silva",
      role: "Batsman" as Role,
      strengths: ["Technique", "Test cricket", "Consistency"],
      weaknesses: ["Pace", "Bounce"],
      recentForm: [71, 82, 75, 65, 78],
    },
    {
      name: "Pathum Nissanka",
      role: "Batsman" as Role,
      strengths: ["Opening", "Technique", "Consistency"],
      weaknesses: ["Aggression", "Death bowling"],
      recentForm: [65, 75, 88, 72, 81],
    },
    {
      name: "Lahiru Kumara",
      role: "Bowler" as Role,
      strengths: ["Pace", "Bounce", "Death bowling"],
      weaknesses: ["Control", "Consistency"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Dilshan Madushanka",
      role: "Bowler" as Role,
      strengths: ["Pace", "Yorkers", "Death overs"],
      weaknesses: ["Length balls", "Experience"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Wanindu Hasaranga",
      role: "All-rounder" as Role,
      strengths: ["Leg-spin", "Batting", "Variation"],
      weaknesses: ["Pace", "Short ball"],
      recentForm: [62, 72, 68, 75, 65],
    },
    {
      name: "Akila Dananjaya",
      role: "Bowler" as Role,
      strengths: ["Off-spin", "Test cricket", "Variations"],
      weaknesses: ["Pace", "Short ball"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Maheesh Theekshana",
      role: "Bowler" as Role,
      strengths: ["Off-break", "Variations", "T20 expertise"],
      weaknesses: ["Pace", "Death overs"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Angelo Mathews",
      role: "All-rounder" as Role,
      strengths: ["Experience", "All-rounder", "Test cricket"],
      weaknesses: ["Age", "Pace bowling"],
      recentForm: [58, 65, 72, 48, 61],
    },
    {
      name: "Charith Asalanka",
      role: "Batsman" as Role,
      strengths: ["Technique", "Consistency", "Potential"],
      weaknesses: ["Pace", "Short balls"],
      recentForm: [68, 75, 62, 78, 71],
    },
    {
      name: "Nuwan Pradeep",
      role: "Bowler" as Role,
      strengths: ["Pace", "Consistency", "Experience"],
      weaknesses: ["Death overs", "Bounce"],
      recentForm: [0, 0, 0, 0, 0],
    },
  ],
  "West Indies": [
    {
      name: "Alick Athanaze",
      role: "Batsman" as Role,
      strengths: ["Technique", "Test batting", "Potential"],
      weaknesses: ["Pace", "Short balls"],
      recentForm: [72, 65, 78, 61, 75],
    },
    {
      name: "Alzarri Joseph",
      role: "Bowler" as Role,
      strengths: ["Pace", "Aggression", "Death bowling"],
      weaknesses: ["Control", "Consistency"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Jason Holder",
      role: "All-rounder" as Role,
      strengths: ["All-rounder", "Pace", "Leadership"],
      weaknesses: ["Batting form", "Spin"],
      recentForm: [58, 68, 52, 72, 61],
    },
    {
      name: "Kyle Mayers",
      role: "Batsman" as Role,
      strengths: ["Aggressive", "Left-hander", "Potential"],
      weaknesses: ["Consistency", "Pace bowling"],
      recentForm: [65, 82, 71, 48, 76],
    },
    {
      name: "Reece Topley",
      role: "Bowler" as Role,
      strengths: ["Pace", "Left-arm angle", "Death"],
      weaknesses: ["Length", "Bounce"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Shamarh Brooks",
      role: "Batsman" as Role,
      strengths: ["Opening", "Consistency", "Technique"],
      weaknesses: ["Pace", "Spin"],
      recentForm: [71, 65, 78, 62, 74],
    },
    {
      name: "Kemar Roach",
      role: "Bowler" as Role,
      strengths: ["Experience", "Swing", "Consistency"],
      weaknesses: ["Pace", "Death overs"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Anderson Phillip",
      role: "Bowler" as Role,
      strengths: ["Pace", "Bounce", "Death bowling"],
      weaknesses: ["Control", "Experience"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Brandon King",
      role: "Batsman" as Role,
      strengths: ["T20 batting", "Aggression", "Potential"],
      weaknesses: ["Pace", "Experience"],
      recentForm: [68, 75, 62, 82, 71],
    },
    {
      name: "Roston Chase",
      role: "All-rounder" as Role,
      strengths: ["All-rounder", "Off-spin", "Batting"],
      weaknesses: ["Pace", "Consistency"],
      recentForm: [62, 68, 75, 58, 70],
    },
    {
      name: "Nicholas Pooran",
      role: "Batsman" as Role,
      strengths: ["Aggressive", "T20 batting", "Power hitting"],
      weaknesses: ["Pace bowling", "Consistency"],
      recentForm: [75, 62, 88, 71, 65],
    },
  ],
  Bangladesh: [
    {
      name: "Mehidy Hasan Miraz",
      role: "All-rounder" as Role,
      strengths: ["Off-spin", "Batting", "All-rounder"],
      weaknesses: ["Pace", "Short ball"],
      recentForm: [65, 72, 68, 75, 61],
    },
    {
      name: "Litton Das",
      role: "Batsman" as Role,
      strengths: ["Opening", "Aggression", "Consistency"],
      weaknesses: ["Pace", "Short balls"],
      recentForm: [68, 75, 62, 82, 71],
    },
    {
      name: "Tanzim Hasan Sakib",
      role: "Bowler" as Role,
      strengths: ["Pace", "Yorkers", "Death bowling"],
      weaknesses: ["Consistency", "Length"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Mahmud Mithun",
      role: "Bowler" as Role,
      strengths: ["Pace", "Accuracy", "Consistency"],
      weaknesses: ["Death overs", "Bounce"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Nazmul Hossain",
      role: "Batsman" as Role,
      strengths: ["Opening", "Technique", "Patience"],
      weaknesses: ["Pace", "Aggression"],
      recentForm: [62, 68, 75, 58, 70],
    },
    {
      name: "Shadman Islam",
      role: "Batsman" as Role,
      strengths: ["Test cricket", "Technique", "Consistency"],
      weaknesses: ["Pace", "Bounce"],
      recentForm: [72, 65, 78, 61, 75],
    },
    {
      name: "Shoriful Islam",
      role: "Bowler" as Role,
      strengths: ["Pace", "Swing", "Death bowling"],
      weaknesses: ["Consistency", "Control"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Taskin Ahmed",
      role: "Bowler" as Role,
      strengths: ["Pace", "Bounce", "Aggression"],
      weaknesses: ["Consistency", "Control"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Mushfiqur Rahim",
      role: "Batsman" as Role,
      strengths: ["Experience", "Technique", "Aggression"],
      weaknesses: ["Pace", "Short balls"],
      recentForm: [71, 62, 78, 65, 76],
    },
    {
      name: "Soumya Sarkar",
      role: "Batsman" as Role,
      strengths: ["Opening", "Aggression", "Left-hander"],
      weaknesses: ["Pace", "Consistency"],
      recentForm: [65, 58, 72, 68, 61],
    },
    {
      name: "Ebadot Hossain",
      role: "Bowler" as Role,
      strengths: ["Pace", "Accuracy", "Experience"],
      weaknesses: ["Death overs", "Bounce"],
      recentForm: [0, 0, 0, 0, 0],
    },
  ],
  Afghanistan: [
    {
      name: "Rashid Khan",
      role: "All-rounder" as Role,
      strengths: ["Leg-spin", "Batting", "Leadership"],
      weaknesses: ["Pace", "Short ball"],
      recentForm: [82, 75, 88, 71, 79],
    },
    {
      name: "Ibrahim Zadran",
      role: "Batsman" as Role,
      strengths: ["Technique", "Consistency", "Test batting"],
      weaknesses: ["Pace", "Aggression"],
      recentForm: [72, 65, 78, 61, 75],
    },
    {
      name: "Mujeeb Ur Rahman",
      role: "Bowler" as Role,
      strengths: ["Off-spin", "Variations", "T20 expertise"],
      weaknesses: ["Pace", "Death overs"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Javed Ahmadi",
      role: "Batsman" as Role,
      strengths: ["Aggressive", "Opening", "Potential"],
      weaknesses: ["Pace", "Consistency"],
      recentForm: [68, 75, 62, 82, 71],
    },
    {
      name: "Aryan Dutt",
      role: "Bowler" as Role,
      strengths: ["Pace", "Accuracy", "Death bowling"],
      weaknesses: ["Consistency", "Control"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Mohammad Nabi",
      role: "All-rounder" as Role,
      strengths: ["Experience", "Off-spin", "Batting"],
      weaknesses: ["Pace", "Age"],
      recentForm: [62, 68, 75, 58, 70],
    },
    {
      name: "Rahmanullah Gurbaz",
      role: "Batsman" as Role,
      strengths: ["Aggressive", "Wicket-keeper", "T20 batting"],
      weaknesses: ["Pace", "Consistency"],
      recentForm: [75, 62, 88, 71, 65],
    },
    {
      name: "Naveen-ul-Haq",
      role: "Bowler" as Role,
      strengths: ["Pace", "Death bowling", "Aggression"],
      weaknesses: ["Control", "Consistency"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Amir Hamza",
      role: "Bowler" as Role,
      strengths: ["Left-arm spin", "Variations", "Experience"],
      weaknesses: ["Pace", "Short ball"],
      recentForm: [0, 0, 0, 0, 0],
    },
    {
      name: "Hazratullah Zazai",
      role: "Batsman" as Role,
      strengths: ["Aggressive", "Power hitting", "Opening"],
      weaknesses: ["Pace", "Consistency"],
      recentForm: [68, 75, 62, 82, 71],
    },
    {
      name: "Farid Ahmad Malik",
      role: "Bowler" as Role,
      strengths: ["Pace", "Accuracy", "Death overs"],
      weaknesses: ["Consistency", "Experience"],
      recentForm: [0, 0, 0, 0, 0],
    },
  ],
}

export function getPlayersByRole(format: Format, role: Role): Player[] {
  return indiaSquad.filter((p) => p.role === role && p.formatAvailability[format])
}

export function getPlayersByFormat(format: Format): Player[] {
  return indiaSquad
    .filter((p) => p.formatAvailability[format])
    .sort((a, b) => {
      const aForm = a.stats[format]
      const bForm = b.stats[format]
      return bForm.runs + bForm.wickets - (aForm.runs + aForm.wickets)
    })
}

export function getPlayersByGroup(group: PlayerGroup, format: Format): Player[] {
  return indiaSquad.filter((p) => p.group === group && p.formatAvailability[format])
}

export function getGroupPlayers(group: PlayerGroup): Player[] {
  return indiaSquad.filter((p) => p.group === group)
}

export interface Match {
  id: string
  format: Format
  opponent: string
  date: string
  time: string
  venue: string
  series: string
  prediction: {
    winProbability: number
    expectedScore: string
  }
}

export const upcomingMatches: Match[] = [
  {
    id: "match1",
    format: "ODI",
    opponent: "Australia",
    date: "Jan 25, 2026",
    time: "02:00 PM",
    venue: "Melbourne Cricket Ground, Australia",
    series: "ODI Series 2026",
    prediction: { winProbability: 78, expectedScore: "280-300" },
  },
  {
    id: "match2",
    format: "T20",
    opponent: "West Indies",
    date: "Jan 28, 2026",
    time: "06:30 PM",
    venue: "Arun Jaitley Stadium, Delhi",
    series: "T20 Series 2026",
    prediction: { winProbability: 82, expectedScore: "160-180" },
  },
  {
    id: "match3",
    format: "Test",
    opponent: "South Africa",
    date: "Feb 01, 2026",
    time: "09:00 AM",
    venue: "Wanderers Stadium, Johannesburg",
    series: "Test Series 2026",
    prediction: { winProbability: 65, expectedScore: "350-380" },
  },
  {
    id: "match4",
    format: "ODI",
    opponent: "England",
    date: "Feb 05, 2026",
    time: "01:30 PM",
    venue: "Lord's Cricket Ground, London",
    series: "ODI Series 2026",
    prediction: { winProbability: 72, expectedScore: "270-290" },
  },
  {
    id: "match5",
    format: "T20",
    opponent: "Pakistan",
    date: "Feb 10, 2026",
    time: "07:00 PM",
    venue: "National Stadium, Karachi",
    series: "T20 Series 2026",
    prediction: { winProbability: 68, expectedScore: "155-175" },
  },
  {
    id: "match6",
    format: "Test",
    opponent: "New Zealand",
    date: "Feb 15, 2026",
    time: "10:30 AM",
    venue: "Basin Reserve, Wellington",
    series: "Test Series 2026",
    prediction: { winProbability: 70, expectedScore: "320-360" },
  },
]

export function getMatchesByFormat(format: Format): Match[] {
  return upcomingMatches.filter((match) => match.format === format)
}

export function getMatchesByOpponent(opponent: string): Match[] {
  return upcomingMatches.filter((match) => match.opponent.toLowerCase().includes(opponent.toLowerCase()))
}
